# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Ember' do
source 'https://github.com/CocoaPods/Specs.git'

pod 'AsyncDisplayKit'
pod 'Firebase'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Firebase/Messaging'
pod 'Firebase/Crash'
end


post_install do |installer|
    app_plist = "Ember/Info.plist"
    plist_buddy = "/usr/libexec/PlistBuddy"
    
    version = `#{plist_buddy} -c "Print CFBundleShortVersionString" "#{app_plist}"`.strip
    
    puts "Updating CocoaPods frameworks' version numbers to #{version}"
    
    installer.pods_project.targets.each do |target|
        `#{plist_buddy} -c "Set CFBundleShortVersionString #{version}" "Pods/Target Support Files/#{target}/Info.plist"`
    end
end

